#+BEGIN_OPTIONS
#+AUTHOR: William F. Schneider
#+TITLE: CBE 60546 Syllabus
#+EMAIL: wschneider@nd.edu
#+LATEX_CLASS_OPTIONS: [11pt]
#+LATEX_HEADER:\usepackage[left=1in, right=1in, top=1in, bottom=1in, nohead]{geometry}
#+LATEX_HEADER:\geometry{margin=1.0in}
#+LATEX_HEADER:\usepackage{amsmath}
#+LATEX_HEADER:\usepackage{graphicx}
#+LATEX_HEADER:\usepackage{epstopdf}
#+LATEX_HEADER:\usepackage{fancyhdr}
#+LATEX_HEADER:\usepackage{hyperref}
#+LATEX_HEADER:\usepackage[labelfont=bf]{caption}
#+LATEX_HEADER:\usepackage{setspace}
#+LATEX_HEADER:\def\dbar{{\mathchar'26\mkern-12mu d}}
#+LATEX_HEADER:\pagestyle{fancy}
#+LATEX_HEADER:\fancyhf{}
#+LATEX_HEADER:\renewcommand{\headrulewidth}{0.5pt}
#+LATEX_HEADER:\renewcommand{\footrulewidth}{0.5pt}
#+LATEX_HEADER:\lfoot{\today}
#+LATEX_HEADER:\cfoot{\copyright\ 2025 W.\ F.\ Schneider}
#+LATEX_HEADER:\rfoot{\thepage}
#+LATEX_HEADER:\title{University of Notre Dame\\Advanced Chemical Engineering Thermodynamics\\(CBE 60553)}
#+LATEX_HEADER:\author{Prof. William F.\ Schneider}
#+LATEX_HEADER:\usepackage{titlesec}
#+LATEX_HEADER:\titlespacing*{\section}
#+LATEX_HEADER:{0pt}{0.6\baselineskip}{0.2\baselineskip}
#+LATEX_HEADER:\titlespacing*{\subsection}
#+LATEX_HEADER:{0pt}{0.6\baselineskip}{0.2\baselineskip}
#+LATEX_HEADER:\titlespacing*{\subsubsection}
#+LATEX_HEADER:{0pt}{0.4\baselineskip}{0.1\baselineskip}

#+EXPORT_EXCLUDE_TAGS: noexport
#+OPTIONS: toc:nil
#+OPTIONS: H:3 num:3
#+OPTIONS: ':t
#+END_OPTIONS

#+BEGIN_EXPORT latex
\begin{center}
\textsc{\Large Advanced Chemical Reaction Engineering (CBE 60546)}\\University of Notre Dame, Fall 2025
Prof.\ Bill Schneider (\email{wschneider@nd.edu})
\end{center}
\begin{tabular*}{\textwidth}{@{\extracolsep{\fill}}l r}
\hline
283 Galvin Hall & Lecture MW 8:35-9:50 am\\
\hline
\end{tabular*}
#+END_EXPORT

* Reactions and Reactors
Chemical reaction engineering is "par excellence the domain of the chemical engineer" (R. Aris)---the analysis and design of chemical reactors (big and small) to economically produce useful products.  The utility of the concepts, though, go well beyond the Haber-Bosch reactors that launched the field or the fluidized catalytic crackers responsible for the wide availability of inexpensive and high quality gasoline.  Reaction engineering ties together virtually all elements of Chemical Engineering, from thermodynamics and chemical kinetics to mass and energy balances to mass and heat transfer.  

We will approach this from a bottom up perspective, starting from the most basic concepts of chemical reactions, reaction thermodynamics, chemical kinetics, and catalysis, to the development and application of mass and energy balances for simple to more complicated reactors. 

I strongly encourage you to keep up with the material and homework, to use the resources available and to find your own resources, and to bring up questions in class. Don’t be bashful: if you don’t understand something, chances are that many of your classmates (and quite possibly your instructor!) don’t either.

* Text
There are many good reaction engineering texts. We won't use or follow any one in particular. Some that I find useful include: 

- Hill and Root, /Introduction to Chemical Engineering Kinetcs & Reactor Design/, 2nd edition, Wiley 2014
- Davis and Davis, /Fundamentals of Chemical Reaction Engineering/, McGraw-Hill. Available online [[https://authors.library.caltech.edu/25070/][here]].
- Rawlings and Ekerdt, /Chemical Reactor Analysis and Design Fundamentals/, 2nd edition, Nob Hill. Useful information [[https://sites.engineering.ucsb.edu/~jbraw/chemreacfun/][here]].
- Schmidt, /The Engineering of Chemical Reactions/, 2nd edition, Oxford 2005. Available online [[https://app.knovel.com/kn/resources/kpECRE0001/toc][here]].

* Format
The topics will be presented in a series of self-contained lectures as outlined on the website. Lecture notes for each lecture will be posted on-line. Attendance is expected, and you should be prepared to ask and answer questions. *All electronic devices will be turned off and put away during lecture.*

** Brief Outline of Course Topics (aspirational!)
1. Stoichiometry
2. Chemical Thermodynamics and Equilibria
3. Empirical Kinetics
4. Molecular Basis of Chemical Kinetics
5. Mechanisms of Chemical Reactions
6. Heterogeneous Reactions and Catalysis
7. Liquid Phase Reactions-maybe
8. Ideal Reactor Design
9. Reactor Optimization
10. Non-isothermal Reactors
11. Non-ideal flow
12. Catalytic reactor design
13. Bioreactors

* Online Resources
This syllabus, the homework assignments and solutions, and written lecture notes are available on the web at [[https://github.com/wmfschneider/CBE60546]].  If you want to get your own copy of all this material and understand a bit about how git works, see [[http://rogerdudler.github.io/git-guide/]].  Or just download files directly from the git site. The source files are written using Org Mode ([[https://orgmode.org/]]), but you can read them using a regular text editor if you want to see under the hood.

A course calendar is available on Google at [[https://calendar.google.com/calendar/b/1?cid=NWJwN2pmMjI5bTdoYmFvM2R0cXM2NjYzOThAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ][WFS Courses]].

* Homework
Ten problem sets will be distributed during the semester and will be due at the beginning of class on dates to be announced. The problem sets will be designed to reinforce your knowledge and ability to apply the course material.  *Assignments turned in late will automatically lose 20%, and those turned in after the solutions are posted will not be accepted.*  Your lowest two scores on homework will be dropped.  You may discuss the homework with your classmates, but *what you turn in must be your own work.* You will turn in your homework on [[https://www.gradescope.com/courses/933965][Gradescope]].

** Jupyter/Python
Homework will be distributed as [[https://jupyter.org/][Jupyter notebooks]] (https://jupyter.org), an open source computing notebook environment that works within a web browser. Jupyter allows one to do among other things, create and execute [[https://www.python.org/][Python]] (https:/www.python.org) programs, which are similar in syntax to Matlab. The easiest way to work within a notebook is through Google's [[https://colab.research.google.com/notebooks/welcome.ipynb][Colaboratory]] (https://colab.research.google.com/notebooks/welcome.ipynb), a web-based platform, integrated with your Google drive, that allows you to create and execute notebooks without installing anything on your computer. Alternatively, you can download Jupyter and Python as one distribution, at [[http://anaconda.com/download]]. 

You are not required to write solutions within a notebook. Clear, hand-written solutions are acceptable and may even teach you the material more effectively.
** Good practices
*Always* start solutions on a piece of paper. If the solution requires some python code, first write down pseudocode before creating in a notebook. 

* Homework Defense
To help me get to know you and how you are doing with the course, after each homework assignment two of you will be chosen at random to meet with me to discuss your homework. Defenses will be in my office during office hours.

* Grading
Grades will be based on the homework (40%) and three exams (60%).

* Academic honesty
Should go without saying. This class follows the binding Code of Honor at Notre Dame.  Any cheating or misrepresenting of work as your own will be dealt with according to the policies of the University.  See https://honorcode.nd.edu/.

Within that policy, you are welcome and even encouraged to take advantage of modern online resources, including generative large language models like [[https://chatgpt.comm][ChatGPT]] or [[https://gemini.google.com/app][Gemini]], to find information or generate code. Document your usage of these or any resources in whatever you turn in, be aware that they are fallible, and be prepared to take responsibility for and defend whatever you turn in as your work. Further, you will work with paper and pencil on exams.

* Teaching Assistants and Office Hours

| Henry Lee      | [[mailto:slee75@nd.edu][slee75@nd.edu]]     | F 2-3  | ??? NSH |
| Bill Schneider | [[mailto:wschneider@nd.edu][wschneider@nd.edu]] | T 3-4  | 370 NSH |

* Health and Well-Being
Resources for students experiencing stress or difficulty coping are available at [[http://care.nd.edu]]. 

* Course calendar
#+CAPTION: Tentative Course Calendar
|----------+--------------------|
| 8/25     | 8/27               |
| Welcome! | *Python notebooks* |
|----------+--------------------|
| 9/1      | 9/3                |
|          | *HW 1*             |
|----------+--------------------|
| 9/8      | 9/10               |
|          | *HW 2*             |
|----------+--------------------|
| 9/15     | 9/17               |
|          | *HW 3*             |
|----------+--------------------|
| 9/22     | 9/24               |
| *Exam 1* |                    |
|----------+--------------------|
| 9/29     | 10/1               |
|          | *HW 4*             |
|----------+--------------------|
| 10/6     | 10/8               |
|          | *HW 5*             |
|----------+--------------------|
| 10/13    | 10/15              |
|          | *HW 6*             |
|----------+--------------------|
| 10/20    | 10/22              |
| *BREAK*  | *BREAK*            |
|----------+--------------------|
| 10/27    | 10/29              |
|          | *HW 7*             |
|----------+--------------------|
| 11/3     | 11/5               |
| *Exam 2* |                    |
|----------+--------------------|
| 11/10    | 11/12              |
|          | *HW 8*             |
|----------+--------------------|
| 11/17    | 11/19              |
|          |                    |
|----------+--------------------|
| 11/24    | 11/26              |
| *HW 9*   | *Thanksgiving*     |
|----------+--------------------|
| 12/1     | 12/3               |
|          | *HW 10*            |
|----------+--------------------|
| 12/8     | 12/10              |
|          | *HW 11*            |
|----------+--------------------|
| 12/15    | 12/15              |
|          | *Final Exam*       |
|----------+--------------------|
