#+BEGIN_OPTIONS
#+AUTHOR: William F. Schneider
#+TITLE: CBE 60546 Syllabus
#+EMAIL: wschneider@nd.edu
#+LATEX_CLASS_OPTIONS: [11pt]
#+LATEX_HEADER:\usepackage[left=1in, right=1in, top=1in, bottom=1in, nohead]{geometry}
#+LATEX_HEADER:\geometry{margin=1.0in}
#+LATEX_HEADER:\usepackage{amsmath}
#+LATEX_HEADER:\usepackage{graphicx}
#+LATEX_HEADER:\usepackage{epstopdf}
#+LATEX_HEADER:\usepackage{fancyhdr}
#+LATEX_HEADER:\usepackage{hyperref}
#+LATEX_HEADER:\usepackage[labelfont=bf]{caption}
#+LATEX_HEADER:\usepackage{setspace}
#+LATEX_HEADER:\def\dbar{{\mathchar'26\mkern-12mu d}}
#+LATEX_HEADER:\pagestyle{fancy}
#+LATEX_HEADER:\fancyhf{}
#+LATEX_HEADER:\renewcommand{\headrulewidth}{0.5pt}
#+LATEX_HEADER:\renewcommand{\footrulewidth}{0.5pt}
#+LATEX_HEADER:\lfoot{\today}
#+LATEX_HEADER:\cfoot{\copyright\ 2017 W.\ F.\ Schneider}
#+LATEX_HEADER:\rfoot{\thepage}
#+LATEX_HEADER:\title{University of Notre Dame\\Advanced Chemical Engineering Thermodynamics\\(CBE 60553)}
#+LATEX_HEADER:\author{Prof. William F.\ Schneider}
#+LATEX_HEADER:\usepackage{titlesec}
#+LATEX_HEADER:\titlespacing*{\section}
#+LATEX_HEADER:{0pt}{0.6\baselineskip}{0.2\baselineskip}
#+LATEX_HEADER:\titlespacing*{\subsection}
#+LATEX_HEADER:{0pt}{0.6\baselineskip}{0.2\baselineskip}
#+LATEX_HEADER:\titlespacing*{\subsubsection}
#+LATEX_HEADER:{0pt}{0.4\baselineskip}{0.1\baselineskip}

#+EXPORT_EXCLUDE_TAGS: noexport
#+OPTIONS: toc:nil
#+OPTIONS: H:3 num:3
#+OPTIONS: ':t
#+END_OPTIONS

#+BEGIN_EXPORT latex
\begin{center}
\textsc{\Large Advanced Chemical Reaction Engineering (CBE 60546)}\\University of Notre Dame, Fall 2021
\end{center}
\begin{tabular*}{\textwidth}{@{\extracolsep{\fill}}l r}
\hline
Prof.\ Mark McCready (\email{mjm@nd.edu})   & Classroom: 118 DBRT\\
Prof.\ Bill Schneider (\email{wschneider@nd.edu}) & Lecture MWF 10:30-11:20\\
\hline
\end{tabular*}
#+END_EXPORT

* Reactions and Reactors
Chemical reaction engineering is "par excellence the domain of the chemical engineer" (R. Aris)---the analysis and design of chemical reactors (big and small) to economically produce useful products.  The utility of the concepts, though, go well beyond the Haber-Bosch reactors that launched the field or the fluidized catalytic crackers responsible for the wide availability of inexpensive and high quality gasoline.  Reaction engineering ties together virtually all elements of Chemical Engineering, from thermodynamics and chemical kinetics to mass and energy balances to mass and heat transfer.  

We will approach this from a bottom up perspective, starting from the most basic concepts of chemical reactions, reaction thermodynamics, and chemical kinetics, to the development and application of mass and energy balances for simple to more complicated reactors. 

We strongly encourage you to keep up with the material and homework, to use the resources available and to find your own resources, and to bring up questions in class. Don’t be bashful: if you don’t understand something, chances are that many of your classmates (and quite possibly your instructor!) don’t either.

* Text
** Primary
- Hill and Root, /Introduction to Chemical Engineering Kinetcs & Reactor Design/, 2nd edition, Wiley 2014
** Supplementary
- Davis and Davis, /Fundamentals of Chemical Reaction Engineering/, McGraw-Hill. Available online [[https://authors.library.caltech.edu/25070/][here]].

* Web
This syllabus, reading assignment, the homework assignments and solutions, a course outline, and supplementary materials are available on the web at [[https://github.com/wmfschneider/CBE60546]].

* Format
The topics will be presented in a series of self-contained lectures as outlined on the website. Lecture notes for each lecture will be posted on-line. Attendance is expected, and you should be prepared to ask and answer questions.

* Topics
1. Stoichiometry
2. Chemical Thermodynamics and equilibria
3. Empirical kinetics
4. Molecular Basis of Chemical Kinetics
5. Mechanisms of Chemical Reactions
6. Heterogeneous Reactions and Catalysis
7. Liquid Phase Reactions
8. Ideal Reactor Design
9. Reactor Optimization
10. Non-isothermal Reactors
11. Non-ideal Flow
12. Catalytic Reactor Design
13. Bioreactors

* Homework
Ten problem sets will be distributed during the semester and will be due at the beginning of class on dates to be announced. The problem sets will be designed to reinforce your knowledge and ability to apply the course material.  *Assignments turned in late will automatically lose 20%, and those turned in after the solutions are posted will not be accepted.*  Your lowest two score on homework will be dropped.  You may discuss the homework with your classmates, but *what you turn in must be your own work.*

Homework will in general require some computations. You may write out solutions by hand or you may use Python or Mathematica notebooks. In any case, the solution of each problem must begin with a complete description of the problem, and the solution must be structured for ease of interpretation by the instructor and TAs.

* Grading
Grades will be based on the homework (30%), two in-class exams (20%), and two out-of-class exams  (50%).

* Academic honesty
Should go without saying. Any cheating or misrepresenting of work as your own will be dealt with according to the Honor Code policies of the University. WE reserve the right to relocate any students during an examination at my discretion.

* Professional courtesy
As a courtesy to the instructor and your classmates, please refrain from
texting, web browsing, tweeting, updating, or using your phone or laptop for any
purpose during class time.  If you must use an electronic device, excuse
yourself from class.

* Office hours
The instructor will be available Wednesdays 3:30-4:30 or by appointment to discuss the course and homework.  Teaching assistants Jeonghyun Ko (jko1@nd.edu) and Tanner Corrado (tcorrado@nd.edu) will be available at times to be announced.


#+CAPTION: Tentative Course Calendar
|----------+---------+-------------+-------+---------+----------------+----------------|
| 8/23     | 8/25    | 8/27        |       | 10/25   | 10/27          | 10/29          |
| Welcome! |         |             | XXXXX |         | *HW 6*         |                |
|----------+---------+-------------+-------+---------+----------------+----------------|
| 8/30     | 9/1     | 9/3         |       | 11/1    | 11/3           | 11/5           |
|          | *HW 1*  |             |       |         | *HW 7*         |                |
|----------+---------+-------------+-------+---------+----------------+----------------|
| 9/6      | 9/8     | 9/10        |       | 11/8    | 11/10          | 11/12          |
|          | *HW 2*  |             |       |         | *HW 8*         | *Exam 3*       |
|----------+---------+-------------+-------+---------+----------------+----------------|
| 9/13     | 9/15    | 9/17        |       | 11/15   | 11/17          | 11/19          |
|          | *HW 3*  | *Exam 1*    |       |         |                |                |
|----------+---------+-------------+-------+---------+----------------+----------------|
| 9/20     | 9/22    | 9/24        |       | 11/22   | 11/24          | 11/26          |
|          |         | *Grad Symp* |       | *HW 9*  | *Thanksgiving* | *Thanksgiving* |
|----------+---------+-------------+-------+---------+----------------+----------------|
| 9/27     | 9/29    | 10/1        |       | 11/29   | 12/1           | 12/3           |
|          | *HW 4*  |             |       |         |                |                |
|----------+---------+-------------+-------+---------+----------------+----------------|
| 10/4     | 10/6    | 10/8        |       | 12/6    | 12/8           | 12/10          |
|          | *HW 5*  |             |       | *HW 10* | *Last class*   | *Study day*    |
|----------+---------+-------------+-------+---------+----------------+----------------|
| 10/11    | 10/13   | 10/15       |       | 12/13   | 12/15          |                |
| *Exam 2* |         |             |       |         | *Final Exam*   |                |
|----------+---------+-------------+-------+---------+----------------+----------------|
| 10/18    | 10/20   | 10/22       |       |         |                |                |
| *BREAK*  | *BREAK* | *BREAK*     |       |         |                |                |
|----------+---------+-------------+-------+---------+----------------+----------------|
