#+BEGIN_OPTIONS
#+AUTHOR: William F. Schneider
#+TITLE: CBE 60546 Homework
#+EMAIL: wschneider@nd.edu
#+LATEX_CLASS_OPTIONS: [11pt]
#+LATEX_HEADER:\usepackage[left=1in, right=1in, top=1in, bottom=1in, nohead]{geometry}
#+LATEX_HEADER:\geometry{margin=1.0in}
#+LATEX_HEADER:\usepackage{hyperref}
#+LATEX_HEADER:\usepackage{amsmath}
#+LATEX_HEADER:\usepackage{graphicx}
#+LATEX_HEADER:\usepackage{epstopdf}
#+LATEX_HEADER:\usepackage{fancyhdr}
#+LATEX_HEADER:\pagestyle{fancy}
#+LATEX_HEADER:\fancyhf{}
#+LATEX_HEADER:\usepackage[labelfont=bf]{caption}
#+LATEX_HEADER:\usepackage{setspace}
#+LATEX_HEADER:\setlength{\headheight}{10.2pt}
#+LATEX_HEADER:\setlength{\headsep}{20pt}
#+LATEX_HEADER:\renewcommand{\headrulewidth}{0.5pt}
#+LATEX_HEADER:\renewcommand{\footrulewidth}{0.5pt}
#+LATEX_HEADER:\lfoot{\today}
#+LATEX_HEADER:\cfoot{\copyright\ 2021 W.\ F.\ Schneider}
#+LATEX_HEADER:\rfoot{\thepage}
#+LATEX_HEADER:\chead{\bf{Advanced Chemical Reaction Engineering (CBE 60546)\vspace{12pt}}}
#+LATEX_HEADER:\lhead{\bf{Homework 2}}
#+LATEX_HEADER:\rhead{\bf{Due September 8, 2021}}
#+LATEX_HEADER:\usepackage{titlesec}
#+LATEX_HEADER:\titlespacing*{\section}
#+LATEX_HEADER:{0pt}{0.6\baselineskip}{0.2\baselineskip}
#+LATEX_HEADER:\title{University of Notre Dame\\Advanced Chemical Engineering Thermodynamics\\(CBE 60553)}
#+LATEX_HEADER:\author{Prof. William F.\ Schneider}
#+LATEX_HEADER:\usepackage{siunitx}
#+LATEX_HEADER:\usepackage[version=3]{mhchem}
#+LATEX_HEADER:\def\dbar{{\mathchar'26\mkern-12mu d}}

#+EXPORT_EXCLUDE_TAGS: noexport
#+OPTIONS: toc:nil
#+OPTIONS: H:3 num:3
#+OPTIONS: ':t
#+END_OPTIONS

\noindent *Carefully and neatly document your answers.  You may use a mathematical solver like Jupyter/iPython. Use plotting software for all plots.*

* Key ideas :noexport:
- multiple equilibria
- Le'Chatlier principle

* Shale, shale everywhere
** Your nation has stumbled upon an enormous reserve of ethane (that's really true!), which you propose to use as a feedstock to produce ethylene, acetylene, and hydrogen via thermal dehydrogenation:

#+BEGIN_CENTER
\ce{ C2H6 (g) -> C2H4(g) + H2 (g) }

\ce{C2H6 (g) -> C2H2 (g) + 2 H2 (g) }
#+END_CENTER
\noindent The thermodynamic data [[./HW2-thermo.csv][here]] is from the [[https://onesearch.library.nd.edu/permalink/f/1phik6l/ndu_aleph002720619][CRC Handbook]] and is based on a \SI{1}{bar} standard state. All the gases can be considered to be ideal over the range of interest here.

1. Plot the standard state enthalpy of ethane vs $T$ from $600$ to \SI{1200}{K}. What does the slope of the plot correspond to?

2. Plot the standard state entropy of ethane vs $T$ from $600$ to \SI{1200}{K}. What does the slope of the plot correspond to?

3. Consider the ethane to ethylene reaction. Plot the standard state reaction enthalpy, $T$ times the standard state reaction entropy, and the standard state reaction Gibbs energy vs $T$ from $600$ to \SI{1200}{K}.

4. What do the plots tell you about the conditions necessary to run these reactions thermally? About what contributes to the free energy change with $T$?

5. Plot the free energy of the ethane to ethylene reaction vs ethane conversion at $800$, $1000$, and \SI{1200}{K} and \SI{1}{bar}.  Determine the equilibrium conversion of ethane at each temperature if this was the only reaction that occurs.

6. Imagine a semi-permeable membrane through which you could control the partial pressure (chemical potential) of hydrogen in a reaction vessel. Plot the mole fractions of ethane and ethylene as a function of $\ln P_\ce{H2}$ at \SI{1000}{K}. (Assume the \ce{H2} does not contribute to the total moles in the vessel.)

7. Now consider both reactions simultaneously. Determine the equilibrium ratio of ethylene to acetylene,  starting from pure ethane, at \SI{1000}{K} and $1$, $10$, and \SI{100}{bar} total pressure (again, assume ideal behavior at all conditions).  Can you explain the result?


* Langmuir adsorption
** The table below shows the mass of carbon monoxide taken up by a 10%(m/m) Ru on alumina sample (i.e., particles of Ru on an inert support) as a function of \ce{CO} pressure at \SI{100}{\celsius}. CO is known to only adsorb on Ru at these conditions.

| $P_\text{CO}  (torr)            |  100 |  150 |  200 |  250 |  300 |  400 |
| CO adsorbed (\mu{}mol/ g sample | 1.28 | 1.63 | 1.77 | 1.94 | 2.06 | 2.21 |

1. Plot the data and use non-linear regression to estimate the value of the uptake equilibrium constant.
2. Plot the model error vs pressure. Do you have confidence in the model?
3. Use the data to estimate the fraction of exposed Ru atoms.


